title: "Future Financial Planning Tools for Consumers"
author: Ignace Decocq  # The author of the book
logo: pipe.jpg
execute:
  execute_notebooks: force


bibtex_bibfiles:
   - referencess.bib



parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution




  
